spring.application.name=job_portal

logging.pattern.console=${CONSOLE_LOG_PATTERN: %green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %cyan(%msg%n)}
logging.level.com.blackhat.job_portal = ${LOG_LEVEL : INFO}

logging.group.jobportal_error = com.blackhat.job_portal.security, com.blackhat.job_portal.contact
logging.level.jobportal_error = ${LOG_LEVEL_ERROR : ERROR}

#logging.pattern.file={"timestamp":"%d{yyyy-MM-dd HH:mm:ss}","level":"%p","logger":"%c","message":"%m"}
#logging.file.name = logs/jobportal.org

#spring.h2.console.enabled = true
#spring.h2.console.path = /h2-console

#spring.datasource.url = jdbc:h2:mem:testdb
#spring.datasource.url= jdbc:h2:file:~/jobportal;AUTO_SERVER=true

spring.datasource.url=jdbc:postgresql://localhost:5432/job_portal
spring.datasource.username = postgres
spring.datasource.password = admin
spring.datasource.driver-class-name = org.postgresql.Driver

#spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:sql/jobportal-schema.sql
spring.sql.init.data-locations=classpath:sql/jobportal-data.sql
spring.jpa.show-sql = ${SHOW_SQL:true}
spring.jpa.properties.hibernate.format_sql=${HIBERNATE_FORMAT_SQL:true}
spring.jpa.hibernate.ddl-auto = validate

spring.jpa.properties.hibernate.default_batch-fetch_size = ${DEFAULT_BATCH_FETCH_SIZE : 50}
spring.security.user.name = groot
spring.security.user.password = groot@123
spring.security.user.role = groot,ROLES

#spring.cache.type=caffeine
#spring.cache.cache-names=jobs,companies,roles
#spring.cache.caffeine.spec=maximumSize=5000,expireAfterWrite=1m

cache.jobs.ttl-minutes=10
cache.jobs.max-size=5000
cache.companies.ttl-minutes=10
cache.companies.max-size=500
cache.roles.ttl-days=1
cache.roles.max-size=100

# CORS Configuration
app.cors.allowed-origins=http://localhost:5173,https://dev.jobportal.eazybytes.com
app.cors.allowed-methods=*
app.cors.allowed-headers=*
app.cors.allow-credentials=true
app.cors.max-age=3600

management.endpoint.health.show-details = always
management.server.port=9091
management.endpoints.web.base-path = /jobportal/actuator
management.endpoints.web.exposure.include = *
#management.endpoints.web.exposure.exclude=beans
management.endpoint.configprops.show-values = always

management.info.env.enabled=true
info.app.name=${spring.application.name}
info.app.description=Backend Project for Job Portal backend application
info.app.version=1.0.0
info.app.contact.email=support@jobportal.com
info.developer.name=BlackHatDevelopers

management.endpoint.shutdown.access=unrestricted

management.otlp.metrics.export.url=http://localhost:4318/v1/metrics
management.otlp.metrics.export.step=10s

management.opentelemetry.tracing.export.otlp.endpoint=http://localhost:4318/v1/traces
management.tracing.sampling.probability=1.0

management.opentelemetry.logging.export.otlp.endpoint=http://localhost:4318/v1/logs
