spring.datasource.url=jdbc:postgresql://localhost:5432/job_portal
spring.datasource.username = postgres
spring.datasource.password = admin
spring.datasource.driver-class-name = org.postgresql.Driver

cache.jobs.ttl-minutes=5
cache.companies.ttl-minutes=5

# CORS Configuration
app.cors.allowed-origins=http://localhost:5173,https://jobportal.eazybytes.com