spring.application.name=job_portal

logging.pattern.console=${CONSOLE_LOG_PATTERN: %green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %cyan(%msg%n)}

#spring.h2.console.enabled = true
#spring.h2.console.path = /h2-console

#spring.datasource.url = jdbc:h2:mem:testdb
#spring.datasource.url= jdbc:h2:file:~/jobportal;AUTO_SERVER=true

spring.datasource.url=jdbc:postgresql://localhost:5432/job_portal
spring.datasource.username = postgres
spring.datasource.password = admin
spring.datasource.driver-class-name = org.postgresql.Driver

#spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:sql/jobportal-schema.sql
spring.sql.init.data-locations=classpath:sql/jobportal-data.sql
spring.jpa.show-sql = ${SHOW_SQL:true}
spring.jpa.properties.hibernate.format_sql=${HIBERNATE_FORMAT_SQL:true}
spring.jpa.hibernate.ddl-auto = validate

